name = "SpinWeightedSpheroidalHarmonics"
uuid = "680e17a6-2a17-48fd-ae01-e2b5a643bef0"
version = "1.1.0"
authors = ["Rico Ka Lok Lo"]

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
ApproxFun = "28f2ccd6-bb30-5033-b560-165f7b14dc2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogarithmicNumbers = "aa2f6b4e-9042-5d33-9679-40d3a6b85899"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
AbstractTrees = "0.4.2"
ApproxFun = "^0.13"
LogarithmicNumbers = "^1"
SpecialFunctions = "2.6.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
